schema_version: 1
plugin:
  id: enthusiaplaytime
  name: EnthusiaPlaytime
  main_class: org.enthusia.playtime.PlayTimePlugin
artifact:
  name: enthusiaplaytime-plugin
  jar_path: target/EnthusiaPlaytime.jar
profiles:
  - restart
configs: []
databases: []
dependencies: []
actions: []
